# FarepixelDuels Configuration
# Database options: SQLITE or MYSQL
database:
  type: SQLITE
  sqlite:
    file: farepixelduels.db
  mysql:
    host: localhost
    port: 3306
    database: farepixelduels
    username: root
    password: ''
    useSSL: false

lobby_spawn:
  world: world
  x: -12.89456389822756
  y: 70.0
  z: 3.8954193880905024
  yaw: -22.944885
  pitch: 4.139739

block_place_and_break:
  enabled: true
  worlds:
    - world

duels:
  start_countdown: 15
  waiting_lobby:
    use_lobby_spawn: false
  messages:
    join_format: '%luckperms_prefix% %player% &ehas joined (&b%count%&e/&b%max%&e)!'
    countdown_normal: '&eThe match starts in &e%seconds%&e seconds!'
    countdown_critical: '&eThe match starts in &c%seconds%&e seconds!'
    fight: '&aFight!'
    eliminate: '&e&lEliminate your opponent!'
    opponent_line: '&f&lOpponent: &r%opponent%'
    victory_title: '&6&lVICTORY!'
    victory_subtitle: '&7%winner%&f won the Duel!'
    defeat_title: '&c&lDEFEAT!'
    defeat_subtitle: '&7%winner%&f won the Duel!'
    win_chat: '&eWinner: &a%winner% | &cLoser: &a%loser%'
    coin_reward: 120 #The Coins that the winner will get rewarded after the game finish.

  play_again:
    enabled: true
    slot: 7
    name: '&aPlay Again &7(Right Click)'
    lore:
      - '&7Click to queue again for'
      - '&7the same mode & type!'

  time_limit_seconds:
    default: 300
    classic: 300
    boxing: 180

  boxing:
    hit_to_win: 100

  return_item:
    slot: 8
    name: '&cReturn to Lobby &7(Right Click)'
    lore: '&7Right-click to leave to the lobby!'
    enabled: true
    command: leave

  scoreboard:
    enabled: true
    server_name: www.farepixel.fun
    waiting_title: '&e&lDUELS'
    playing_title: '&e&lDUELS'
    waiting_lines:
      - '&7%date% &8%tag%'
      - ''
      - '&fMap: &a%arena%'
      - '&fPlayers: &a%players%/%max%'
      - ''
      - '%status%'
      - ''
      - '&fMode: &a%mode%'
      - '&fVersion: &7v1.0'
      - ''
      - '&e%server%'
    playing_lines:
      - '&7%date% &8%tag%'
      - ''
      - '&fTime: &a%timeout%'
      - ''
      - '&fOpponent:'
      - '&a%opponents%'
      - ''
      - '&fMode: &a%mode%'
      - '&fOverall Winstreak: &a%winstreak%'
      - '&fBest Winstreak: &a%best_winstreak%'
      - ''
      - '&e%server%'

scoreboards:
  default:
    playing:
      - '&7Mode: &e%mode%'
      - '&7Map: &a%map%'
      - '&7Opponent: &c%opponent%'
      - '&7Time Left: &f%time%'
  boxing:
    playing:
      - '&e&lBOXING DUEL'
      - '&7You: &a%hits%'
      - '&7Opponent: &c%opponent_hits%'
      - '&7Time Left: &f%time%'